# These are supported funding model platforms

github: [daimor]
custom: https://www.paypal.me/daimor
patreon: daimor
ko_fi: daimor
# custom: https://liberapay.com/daimor/donate
# custom: https://money.yandex.ru/to/410018360447959
